"""Unique for company owner

Revision ID: 51e040a63d97
Revises: d88f3d1b2282
Create Date: 2024-02-27 07:35:18.466999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e040a63d97'
down_revision: Union[str, None] = 'd88f3d1b2282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['own_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
