"""The is_first_loggedin added

Revision ID: ba275afd0879
Revises: 637d740fa95b
Create Date: 2024-02-23 19:29:19.605308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba275afd0879'
down_revision: Union[str, None] = '637d740fa95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_first_login', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_first_login')
    # ### end Alembic commands ###
